apiVersion: batch/v1
kind: Job
metadata:
  name: azure-storage-example
spec:
  template:
    spec:
      containers:
      - name: azure-storage-example
        image: tstahlfsu/azure-storage-example:latest
        imagePullPolicy: "Always"
        env:
          - name: AZURE_STORAGE_ACCOUNT_KEY
            valueFrom:
              secretKeyRef:
                name: azurekey
                key: key
                optional: false 

          - name: AZURE_STORAGE_ACCOUNT_NAME
            valueFrom:
              secretKeyRef:
                name: azurekey
                key: name
                optional: false
      restartPolicy: Never
  backoffLimit: 2
