apiVersion: batch/v1
kind: Job
metadata:
  name: azure-storage-example
spec:
  template:
    spec:
      containers:
      - name: azure-storage-example
        image: tstahlfsu/azure-storage-example:latest
        imagePullPolicy: "Always"
        env:
          - name: PRIMARY_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: appviastor3
                key: key
                optional: false 

          - name: NAME
            valueFrom:
              secretKeyRef:
                name: appviastor3
                key: name
                optional: false
      restartPolicy: Never
  backoffLimit: 2
